Went with regular test runner

diff --git a/backend/tests/test-all b/backend/tests/test-all
--- a/backend/tests/test-all
+++ b/backend/tests/test-all
@@ -93,7 +93,8 @@ fi
 if (( unittests ))
 then
   echo "Running unit tests with coverage..."
-  coverage run --source=. -m unittest discover -s tests/unittests -p "test_*.py" || fail_to "run unit tests"
+  coverage run --source='.' manage.py test || fail_to "run unit tests"
+  # coverage run --source='.' -m unittest discover -s tests/unittests -p "test_*.py" || fail_to "run unit tests"
   
   echo "Generating coverage report..."
   coverage report -m || warn_couldnt "generate coverage report"
